server:
  port: 8080

build.name: @project.name@
build.version: @project.version@
 # DB_HOSTNAME=localhost;DB_PORT=3306;DB_NAME=abc_tech;DB_USERNAME=root;DB_PASSWORD=Fiap1234
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/abc_tech
    username: root
    password: Fiap1234
